# Generated by Django 2.1rc1 on 2020-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdeails',
            name='active_flag',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
